# Generated by Django 5.2.1 on 2025-05-28 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion_esperada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
