# Generated by Django 5.2.1 on 2025-05-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_prestamo_fecha_devolucion_esperada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['-fecha_prestamo'], 'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_esperada',
            field=models.DateField(),
        ),
    ]
