# Generated by Django 5.2.1 on 2025-05-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_prestamo_devuelto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='devuelto',
        ),
    ]
