# Generated by Django 5.2.1 on 2025-06-06 21:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_libro_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
