# Generated by Django 5.2.1 on 2025-06-26 16:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_alter_libro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
